# Definir variables iniciales
@serverUrl = http://localhost:3000
@id = c72ebfb9-90bb-4d6c-ad9b-5c71fefe5159

### Obtener todos los coches
GET {{serverUrl}}/cars

### Obtener un coche por id
GET {{serverUrl}}/cars/{{id}}

### Crear un coche nuevo
POST {{serverUrl}}/cars
Content-Type: application/json

{
  "brand": "Volvo",
  "model": "XC40"
}

### Actualizar un coche
PATCH {{serverUrl}}/cars/{{id}}
Content-Type: application/json

{
  "id": {{id}},
  "brand": "Toyota",
  "model": "Corolla"
}

### Borrar un coche
DELETE {{serverUrl}}/cars/{{id}}

