# Definir variable id:
@id = bbccb59f-6fc0-4faa-b1db-25ca1e66f7f8

### Obtener todos los coches
GET http://localhost:3000/cars

### Obtener un coche por id
GET http://localhost:3000/cars/{{id}}

### Crear un coche nuevo
POST http://localhost:3000/cars
Content-Type: application/json

{
  "brand": "Volvo",
  "model": "XC40",
  "puertas": 3
}

### Actualizar un coche
PATCH http://localhost:3000/cars/{{id}}
Content-Type: application/json

{
  "id": {{id}},
  "brand": "Toyota",
  "model": "Corolla"
}

### Borrar un coche
DELETE http://localhost:3000/cars/{{id}}

