# Definir variables iniciales
@serverUrl = http://localhost:3000
@prefix = /api/v2
@id = 68b59ddec91d769f19092f76

### Obtener todos los pokemon
GET {{serverUrl}}{{prefix}}/pokemon

### Obtener un pokemon por id
GET {{serverUrl}}{{prefix}}/pokemon/{{id}}

### Crear un pokemon nuevo
POST {{serverUrl}}{{prefix}}/pokemon
Content-Type: application/json

{
    "no": 5,
    "name": "Pikachu"
}

### Actualizar un pokemon
PATCH {{serverUrl}}{{prefix}}/pokemon/{{id}}
Content-Type: application/json

{
    "no": 1,
    "name": "charmander1"
}

### Borrar un pokemon
DELETE {{serverUrl}}{{prefix}}/pokemon/{{id}}

